spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/atl_academy_07
    username: postgres
    password: 12345

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    enabled: 'true'
    path: /swagger-ui.html
